#ifndef LCD_H_

#define LCD_H_

#define LCD_BA 0x4D000000


#define LCDCON1_OFF 	0x00
#define LCDCON1_REG(BA) \
	HW_REG(BA,LCDCON1_OFF)

#define LCDCON2_OFF 	0x04
#define LCDCON2_REG(BA) \
	HW_REG(BA,LCDCON2_OFF)

#define LCDCON3_OFF 	0x08
#define LCDCON3_REG(BA) \
	HW_REG(BA,LCDCON3_OFF)


#define LCDCON4_OFF 	0x0C
#define LCDCON4_REG(BA) \
	HW_REG(BA,LCDCON4_OFF)

#define LCDCON5_OFF 	0x10
#define LCDCON5_REG(BA) \
	HW_REG(BA,LCDCON5_OFF)


#define LCDSADDR1_OFF	0x14
#define LCDSADDR1_REG(BA) \
	HW_REG(BA,LCDSADDR1_OFF)

#define LCDSADDR2_OFF	0x18
#define LCDSADDR2_REG(BA) \
	HW_REG(BA,LCDSADDR2_OFF)


#define LCDSADDR3_OFF	0x1C
#define LCDSADDR3_REG(BA) \
	HW_REG(BA,LCDSADDR3_OFF)


#define REDLUT_OFF		0x20
#define REDLUT_REG(BA) \
	HW_REG(BA,REDLUT_OFF)


#define GREENLUT_OFF	0x24
#define GREENLUT_REG(BA) \
	HW_REG(BA,GREENLUT_OFF)

#define BLUELUT_OFF		0x28
#define BLUELUT_REG(BA) \
	HW_REG(BA,BLUELUT_OFF)

#define DITHMODE_OFF	0x4C
#define DITHMODE_REG(BA) \
	HW_REG(BA,DITHMODE_OFF)

#define TPAL_OFF 		0x50
#define TPAL_REG(BA) \
	HW_REG(BA,TPAL_OFF)


#endif
