#ifndef USB_HOST_CONTROLLER_H_

#define USB_HOST_CONTROLLER_H_

#include "common.h"

#define USB_HOST_CONTROLLER_BA (0x49000000U)

#define HC_REVISION_OFF 				0x00
#define HC_REVISION_REG(BA) \
	HW_REG(BA,HC_REVISION_OFF)

#define HC_CONTROL_OFF 					0x04
#define HC_CONTROL_REG(BA) \
	HW_REG(BA,HC_CONTROL_OFF)

#define HC_COMMON_STATUS_OFF 			0x08
#define HC_COMMON_STATUS_REG(BA) \
	HW_REG(BA,HC_COMMON_STATUS_OFF)

#define HC_INTERRUPT_STATUS_OFF 		0x0C
#define HC_INTERRUPT_STATUS_REG(BA) \
	HW_REG(BA,HC_INTERRUPT_STATUS_OFF)

#define HC_INTERRUPT_ENABLE_OFF 		0x10
#define HC_INTERRUPT_ENABLE_REG(BA) \
	HW_REG(BA,HC_INTERRUPT_ENABLE_OFF)


#define HC_INTERRUPT_DISABLE_OFF 		0x14
#define HC_INTERRUPT_DISABLE_REG(BA) \
	HW_REG(BA,HC_INTERRUPT_DISABLE_OFF)


#define HC_HCCA_OFF 					0x18
#define HC_HCCA_REG(BA) \
	HW_REG(BA,HC_HCCA_OFF)

#define HC_PERIOD_CUTTENT_ED_OFF 		0x1C
#define HC_PERIOD_CUTTENT_ED_REG(BA) \
	HW_REG(BA,HC_PERIOD_CUTTENT_ED_OFF)


#define HC_CONTROL_HEAD_ED_OFF 			0x20
#define HC_CONTROL_HEAD_ED_REG(BA) \
	HW_REG(BA,HC_CONTROL_HEAD_ED_OFF)


#define HC_CONTROL_CURRENT_ED_OFF 		0x24
#define HC_CONTROL_CURRENT_ED_REG(BA) \
	HW_REG(BA,HC_CONTROL_CURRENT_ED_OFF)

#define HC_BULK_HEAD_ED_OFF 			0x28
#define HC_BULK_HEAD_ED_REG(BA) \
	HW_REG(BA,HC_BULK_HEAD_ED_OFF)


#define HC_BULK_CURRENT_ED_OFF 			0x2C
#define HC_BULK_CURRENT_ED_REG(BA) \
	HW_REG(BA,HC_BULK_CURRENT_ED_OFF)

#define HC_DONE_HEAD_OFF 				0x30
#define HC_DONE_HEAD_REG(BA) \
	HW_REG(BA,HC_DONE_HEAD_OFF)


#define HC_RM_INTERVAL_OFF 				0x34
#define HC_RM_INTERVAL_REG(BA) \
	HW_REG(BA,HC_RM_INTERVAL_OFF)

#define HC_FM_REMAINING_OFF 			0x38
#define HC_FM_REMAINING_REG(BA) \
	HW_REG(BA,HC_FM_REMAINING_OFF)

#define HC_FM_NUMBER_OFF 				0x3C
#define HC_FM_NUMBER_REG(BA) \
	HW_REG(BA,HC_FM_NUMBER_OFF)

#define HC_PERIOD_START_OFF 			0x40
#define HC_PERIOD_START_REG(BA) \
	HW_REG(BA,HC_PERIOD_START_OFF)

#define HC_LS_THRESHOLD_OFF 			0x44
#define HC_LS_THRESHOLD_REG(BA) \
	HW_REG(BA,HC_LS_THRESHOLD_OFF)


#define HC_RH_DESCRIPTOR_A_OFF 			0x48
#define HC_RH_DESCRIPTOR_A_REG(BA) \
	HW_REG(BA,HC_RH_DESCRIPTOR_A_OFF)


#define HC_RH_DESCRIPTOR_B_OFF 			0x4C
#define HC_RH_DESCRIPTOR_B_REG(BA) \
	HW_REG(BA,HC_RH_DESCRIPTOR_B_OFF)

#define HC_RH_STATUS_OFF 				0x50
#define HC_RH_STATUS_REG(BA) \
	HW_REG(BA,HC_RH_STATUS_OFF)


#define HC_RH_PORT_STATUS1_OFF 			0x54
#define HC_RH_PORT_STATUS1_REG(BA) \
	HW_REG(BA,HC_RH_PORT_STATUS1_OFF)


#define HC_RH_PORT_STATUS2_OFF 			0x58
#define HC_RH_PORT_STATUS2_REG(BA) \
	HW_REG(BA,HC_RH_PORT_STATUS2_OFF)


#endif
