#ifndef USB_OHCI_H_

#define USB_OHCI_H_

#include "common.h"

#define USB_OHCI_BA 			(0x49000000U)

#define HC_REVISION_OFF 				0x00
#define HC_REVISION_REG(BA) \
	HW_REG(BA,HC_REVISION_OFF)

#define HC_CONTROL_OFF 					0x04
#define HC_CONTROL_REG(BA) \
	HW_REG(BA,HC_CONTROL_OFF)

#define CBSR_0 	0
#define CBSR_1 	BIT0
#define CBSR_2 	BIT1
#define CBSR_3 	(BIT1|BIT0)

#define PLE 	BIT2
#define IE 	 	BIT3
#define CLE 	BIT4
#define BLE 	BIT5

#define HCFS_USB_RESET 			0
#define HCFS_USB_RESUME 		BIT6
#define HCFS_USB_OPERATIONAL 	BIT7
#define HCFS_USB_SUSPEND 		BIT7|BIT6
#define IR 						BIT8
#define RWC 					BIT9
#define RWE 					BIT10


#define HC_COMMAND_STATUS_OFF 			0x08
#define HC_COMMAND_STATUS_REG(BA) \
	HW_REG(BA,HC_COMMAND_STATUS_OFF)

#define HCR BIT0
#define CLF BIT1
#define BLF BIT2
#define OCR BIT3

#define SOC (BIT7|BIT6)

#define HC_INTERRUPT_STATUS_OFF 		0x0C
#define HC_INTERRUPT_STATUS_REG(BA) \
	HW_REG(BA,HC_INTERRUPT_STATUS_OFF)


#define HC_INTERRUPT_ENABLE_OFF 		0x10
#define HC_INTERRUPT_ENABLE_REG(BA) \
	HW_REG(BA,HC_INTERRUPT_ENABLE_OFF)


#define HC_INTERRUPT_DISABLE_OFF 		0x14
#define HC_INTERRUPT_DISABLE_REG(BA) \
	HW_REG(BA,HC_INTERRUPT_DISABLE_OFF)

#define SO 		BIT0
#define WDH 	BIT1
#define SF  	BIT2
#define RD 		BIT3
#define UE 		BIT4
#define FNO  	BIT5
#define RHSC 	BIT6
#define OC 		BIT10
#define MIE 	BIT11

#define HC_HCCA_OFF 					0x18
#define HC_HCCA_REG(BA) \
	HW_REG(BA,HC_HCCA_OFF)

#define HC_PERIOD_CURRENT_ED_OFF 		0x1C
#define HC_PERIOD_CURRENT_ED_REG(BA) \
	HW_REG(BA,HC_PERIOD_CURRENT_ED_OFF)


#define HC_CONTROL_HEAD_ED_OFF 			0x20
#define HC_CONTROL_HEAD_ED_REG(BA) \
	HW_REG(BA,HC_CONTROL_HEAD_ED_OFF)


#define HC_CONTROL_CURRENT_ED_OFF 		0x24
#define HC_CONTROL_CURRENT_ED_REG(BA) \
	HW_REG(BA,HC_CONTROL_CURRENT_ED_OFF)

#define HC_BULK_HEAD_ED_OFF 			0x28
#define HC_BULK_HEAD_ED_REG(BA) \
	HW_REG(BA,HC_BULK_HEAD_ED_OFF)


#define HC_BULK_CURRENT_ED_OFF 			0x2C
#define HC_BULK_CURRENT_ED_REG(BA) \
	HW_REG(BA,HC_BULK_CURRENT_ED_OFF)

#define HC_DONE_HEAD_OFF 				0x30
#define HC_DONE_HEAD_REG(BA) \
	HW_REG(BA,HC_DONE_HEAD_OFF)


#define HC_RM_INTERVAL_OFF 				0x34
#define HC_RM_INTERVAL_REG(BA) \
	HW_REG(BA,HC_RM_INTERVAL_OFF)

#define HC_FM_REMAINING_OFF 			0x38
#define HC_FM_REMAINING_REG(BA) \
	HW_REG(BA,HC_FM_REMAINING_OFF)

#define HC_FM_NUMBER_OFF 				0x3C
#define HC_FM_NUMBER_REG(BA) \
	HW_REG(BA,HC_FM_NUMBER_OFF)

#define HC_PERIOD_START_OFF 			0x40
#define HC_PERIOD_START_REG(BA) \
	HW_REG(BA,HC_PERIOD_START_OFF)

#define HC_LS_THRESHOLD_OFF 			0x44
#define HC_LS_THRESHOLD_REG(BA) \
	HW_REG(BA,HC_LS_THRESHOLD_OFF)


#define HC_RH_DESCRIPTOR_A_OFF 			0x48
#define HC_RH_DESCRIPTOR_A_REG(BA) \
	HW_REG(BA,HC_RH_DESCRIPTOR_A_OFF)


#define HC_RH_DESCRIPTOR_B_OFF 			0x4C
#define HC_RH_DESCRIPTOR_B_REG(BA) \
	HW_REG(BA,HC_RH_DESCRIPTOR_B_OFF)

#define HC_RH_STATUS_OFF 				0x50
#define HC_RH_STATUS_REG(BA) \
	HW_REG(BA,HC_RH_STATUS_OFF)


#define HC_RH_PORT_STATUS1_OFF 			0x54
#define HC_RH_PORT_STATUS1_REG(BA) \
	HW_REG(BA,HC_RH_PORT_STATUS1_OFF)


#define HC_RH_PORT_STATUS2_OFF 			0x58
#define HC_RH_PORT_STATUS2_REG(BA) \
	HW_REG(BA,HC_RH_PORT_STATUS2_OFF)


/**** OHCI functionality ****/


#endif
